config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # establish distinct root for authenticated users
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated do
    root to: 'redirect#redirect', as: :authenticated_root
  end

  # root for unauthenticated users
  root to: redirect('auth/sign_in')

  # scope devise routes under /auth to avoid conflict with User CRUD
  devise_for :users, path: 'auth', controllers: {
    invitations: 'invitations'
  }
  concern :versionable do
    member do
      get :diff
      get :rollback
    end
  end

  devise_scope :user do
    get 'auth/invitations', to: 'invitations#index'
  end

  namespace :api do
    namespace :v1 do
      constraints(format: :json) do
        get 'ok', to: 'base#ok'
        get 'inst', to: 'auth_support#inst'
      end
    end
  end

  get 'ez_proxy_update', to: 'ez_proxy_update#report'
  get 'ez_proxy_update/:inst_code', to: 'ez_proxy_update#report'

  get 'institutions_for_stats', to: 'institutions_for_stats#report'
  get 'resources_for_stats', to: 'resources_for_stats#report'
  get 'vendors_for_stats', to: 'vendors_for_stats#report'
  get 'vendor_statistics_identifier_for_stats/:resource_code', to: 'vendor_statistics_identifier_for_stats#report', as: 'vendor_statistics_identifier_for_stats'

  resources :institutions, concerns: :versionable do
    resources :resources, controller: 'institution_resources', only: :index, as: 'resources'
    resources :sites, controller: 'institution_sites', except: [:destroy, :new, :create], as: 'sites'
    resources :brandings
    resources :features
    resources :widgets
    resources :bento_configs do
      member do
        get :test_config
        get :eds_content_providers
      end
      collection do
        get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'bento_config'}
      end
    end
    resources :configured_bentos do
      collection do
        post :restore_defaults
        get '/view/(:user_view)', to: 'configured_bentos#reorder', as: 'reorder'
        post '/view/:user_view', to: 'configured_bentos#save_reorder', as: 'save_reorder'
        post '/view/:user_view/restore_defaults', to: 'configured_bentos#restore_defaults_for_view', as: 'restore_defaults_for_view'
        get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'configured_bento'}
      end
    end
    collection do
      get '/deleted', to: 'versions#deleted', defaults: {item_type: 'institution'}
    end
    member do
      get :new_new_password
      get :update_password_asap
      get :notify_current_password
      get :notify_new_password
      get :express_links_report
      get :resources_report
      get :glri_resources_report
      get :institution_serial_count_report
      get :edit_institutional
      patch :update_institutional
    end
  end

  resources :sites

  resources :resources, concerns: :versionable do
    collection do
      get '/deleted', to: 'versions#deleted', defaults: {item_type: 'resource'}
    end
    member do
      get :copy
    end
  end

  resources :contacts, concerns: :versionable do
    collection do
      get '/deleted', to: 'versions#deleted', defaults: {item_type: 'contact'}
      delete :bulk_destroy
      get :bulk_destroy_confirm
    end
    member do
      get :notify_current_password
    end
  end

  resources :users do
    collection do
      get '/deleted', to: 'users#deleted'
    end
    post :undelete, on: :member
  end

  resources :institution_groups do
    resources :features
  end

  resources :users, :vendors, :passwords, :notify_groups, :formats, :subjects, :user_views

  resources :allocations, only: %i[index show edit update]
  resources :versions, only: %i[index show] do
    collection do
      get '/:item_type/deleted', to: 'versions#deleted', as: 'deleted'
    end
    member do
      post :undelete
    end
  end

  resources :reports, only: %i[index] do
    collection do
      get :resources_with_html
      get :resources_url_check
      get :institution_group_ips
      get :institution_resources
      get :institution_glri_resources
      get :institution_express_links
      get :glri_contacts
      get :non_glri_institutions
      get :ez_proxy_update
      get :public_libraries_primary_contacts
      get :vendor_resources
      get :allocations_vendor
      get :allocations_institution
      get :allocations_resource
      get :vendors_for_stats
      get :resources_for_stats
      get :institutions_for_stats
      get :vendor_statistics_identifier_for_stats
      get :glri_allocations
      get :inst_user_emails
      get :all_rows_for
      get :overlapping_ip_addresses
      get :institution_features
      get :institution_group_features
      get :institution_group_contacts
      get :galileo_passwords
      get :resource_keywords
      get :wayfinder_keywords
      get :deleted_contacts
      get :stats_for_snapshots
    end
  end

  resources :tools, only: %i[index] do
    collection do
      get :csv_import, to: 'tools#csv_import_tool'
      put :csv_import, to: 'tools#csv_import'
      get :ip_cache_status, to: 'tools#ip_cache_status_tool'
      put :ip_cache_status, to: 'tools#ip_cache_status'
    end
  end

  get 'bentos', to: 'template_view_bentos#index'
  get 'bento_templates', to: 'template_view_bentos#templates'

  if FeatureFlags.enabled? :flexible_bento_templates
    get 'bento_template/:from/fork', to: 'template_view_bentos#fork_template_form', as: 'fork_bento_template_form'
    post 'bento_template/:from/fork', to: 'template_view_bentos#fork_template', as: 'fork_bento_template'
  end

  resources :template_view_bentos do
    collection do
      get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'template_view_bento'}
    end
  end
  resources :predefined_bentos do
    collection do
      get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'predefined_bento'}
    end
  end
  resources :configured_bentos, only:[:show] do
    collection do
      get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'configured_bento'}
    end
  end

  resources :bento_configs, only:[:show] do
    collection do
      get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'bento_config'}
    end
  end

  resources :bento_versions, only: %i[index show] do
    collection do
      get '/:item_type/deleted', to: 'bento_versions#deleted', as: 'deleted'
    end
    member do
      post :undelete
    end
  end

  resources :banners, concerns: :versionable do
    collection do
      get '/deleted', to: 'versions#deleted', defaults: {item_type: 'banner'}
    end
    member do
      post :undelete
    end
  end

  namespace :stats do
    get '/', to: 'stats#index', as: :index
    delete ':period/delete_all/:table_name', to: 'stats#delete_all', as: :delete_all

    get 'daily/index/:table_name', to: 'daily#index', as: :daily_index
    get 'daily/new_accumulate_range/:table_name', to: 'daily#new_accumulate_range', as: :daily_new_accumulate_range
    post 'daily/accumulate_range/:table_name', to: 'daily#accumulate_range', as: :daily_accumulate_range
    get 'daily/new_delete_range/:table_name', to: 'daily#new_delete_range', as: :daily_new_delete_range
    delete 'daily/delete_range/:table_name', to: 'daily#delete_range', as: :daily_delete_range

    get 'monthly/index/:table_name', to: 'monthly#index', as: :monthly_index
    get 'monthly/new_accumulate/:table_name', to: 'monthly#new_accumulate', as: :monthly_new_accumulate
    post 'monthly/accumulate/:table_name', to: 'monthly#accumulate', as: :monthly_accumulate
    get 'monthly/new_delete_range/:table_name', to: 'monthly#new_delete_range', as: :monthly_new_delete_range
    delete 'monthly/delete_range/:table_name', to: 'monthly#delete_range', as: :monthly_delete_range

    #Problems putting these routes in the raw namespace
    get 'raw/index/:table_name', to: 'raw#index', as: :raw_index
    get 'raw/new_import/:table_name', to: 'raw#new_import', as: :raw_new_import
    post 'raw/import/:table_name', to: 'raw#import', as: :raw_import
    get 'raw/new_delete_range/:table_name', to: 'raw#new_delete_range', as: :raw_new_delete_range
    delete 'raw/delete_range/:table_name', to: 'raw#delete_range', as: :raw_delete_range
  end
end

app/models/user.rb
# frozen_string_literal: true

# GALILEO Admin site user
class User < ApplicationRecord
  # region includes
  include PgSearch::Model
  include InstitutionFilterable
  # endregion

  # region constants
  VALID_ROLES = %w[admin institutional helpdesk].freeze
  VALID_SUBROLES = {
    admin: [],
    institutional: %w[advanced portal],
    helpdesk: []
  }.freeze
  # endregion

  # region relationships
  has_and_belongs_to_many :institutions
  has_many :versions, :class_name => 'Version', :foreign_key => 'whodunnit'
  has_many :contacts, primary_key: 'email', foreign_key: 'email'
  # endregion

  # region  devise
  devise :database_authenticatable, :recoverable, :rememberable, :validatable, :invitable, validate_on_invite: true
  # endregion

  #region callbacks
  before_validation :clean_subroles
  # end_region

  # region validations
  validates_presence_of :role, :first_name, :last_name
  validates_inclusion_of :role, in: VALID_ROLES
  validate :allowed_subroles
  # endregion

  # region pg_search
  pg_search_scope :search_for,
                  against: %i[email role first_name last_name],
                  using: {
                    tsearch: {
                      dictionary: 'english',
                      prefix: true
                    }
                  }
  # endregion

  #region filterrific
  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters:
      %i[sorted_by text_search with_role with_subroles with_institutions]
  )
  # endregion

  # region scopes
  scope :text_search, ->(query) { search_for query }


  scope :active, lambda {
    where('deleted_at IS NULL AND (invitation_sent_at IS NULL OR invitation_accepted_at IS NOT NULL)')
  }

  scope :deleted, lambda {
    where.not(deleted_at: nil)
  }

  scope :pending_invitation_response, lambda {
    where('invitation_sent_at IS NOT NULL AND invitation_accepted_at IS NULL')
  }

  scope :sorted_by, lambda { |sort_option|
    direction = /desc$/.match?(sort_option) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at/ then order "users.created_at #{direction}"
    when /^updated_at/ then order "users.updated_at #{direction}"
    when /^email/ then order "users.email #{direction}"
    when /^role/ then order "users.role #{direction}"
    when /^first_name/ then order "users.first_name #{direction}"
    when /^last_name/ then order "users.last_name #{direction}"

    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  scope :with_role, lambda { |role|
    next unless role

    where(role: role)
  }

  scope :with_subroles, lambda { |*subroles|
    roles = subroles.flatten.reject(&:blank?)
    next if roles.empty?

    where('subroles @> ARRAY[?]::varchar[]', roles)
  }

  many_to_many_institution_scope :with_institutions
  # endregion

  # region public_methods
  def has_role?(role)
    self.role == role
  end
  def has_subrole?(role)
    self.include? role
  end

  def all_roles
    roles = [role]
    roles + subroles
  end


  def admin?
    role == 'admin'
  end

  def non_admin?
    !admin?
  end

  def institutional?
    role == 'institutional'
  end

  def helpdesk?
    role == 'helpdesk'
  end

  def status
    if deleted_at.nil? && (invitation_sent_at.nil? || !invitation_accepted_at.nil?)
      'Active'
    elsif !invitation_sent_at.nil? && invitation_accepted_at.nil?
      'Invited'
    elsif !deleted_at.nil?
      'Deleted'
    else
      'Unknown'
    end
  end

  # instead of deleting, indicate the user requested a delete & timestamp it
  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  # ensure user account is active
  def active_for_authentication?
    super && !deleted_at
  end

  # provide a custom message for a deleted account
  def inactive_message
    !deleted_at ? super : :deleted_account
  end

  def name
    "#{first_name} #{last_name}"
  end

  def name_with_email
    "#{name} (#{email})"
  end

  def clean_subroles
    self.subroles = subroles.uniq.reject(&:blank?)
  end

  def allowed_subroles
    return unless subroles.any?

    bad_subroles = subroles - VALID_SUBROLES[role.to_sym]

    return unless bad_subroles&.any?

    errors.add(:subroles, "invalid subrole for this role: #{bad_subroles.join}")
  end
  # endregion

  # region class_methods
  def self.sort_options
    [
      ['Recently Created', 'created_at_desc'],
      ['Recently Updated', 'updated_at_desc']
    ]
  end

  # Used to populate user emails for filteriffic
  def self.options_for_select
    order('LOWER(email)').map { |e| [e.email, e.id] }
  end
  # endregion
end

app/helpers/template_view_bentos_helper.rb
# frozen_string_literal: true

# TemplateViewBento related helpers
module TemplateViewBentosHelper
  def general_template_view_bento_fields(template_view_bento)
    {
      I18n.t('activerecord.attributes.template_view_bento.template_name') => template_view_bento.template_name,
      I18n.t('activerecord.attributes.template_view_bento.user_view') => template_view_bento.user_view,
      I18n.t('activerecord.attributes.template_view_bento.predefined_bento_id') => link_to(
        template_view_bento.predefined_bento.disambiguated_name,
        template_view_bento.predefined_bento),
      I18n.t('activerecord.attributes.template_view_bento.default_order') => template_view_bento.default_order,
      I18n.t('activerecord.attributes.template_view_bento.shown_by_default') => template_view_bento.shown_by_default,
      I18n.t('activerecord.attributes.contact.created_at') => template_view_bento.created_at,
      I18n.t('activerecord.attributes.contact.updated_at') => template_view_bento.updated_at
    }
  end
end

app/views/template_view_bentos/_form.html.erb
<%= bootstrap_form_for @template_view_bento do |f| %>
  <%= f.alert_message "Errors found that prevented this template view bento from being saved:" %>

  <%# General fields %>
  <div class="card mb-3" data-template-view-bento-form>
    <div class="card-header">General</div>
    <div class="card-body">
        <% if @template_view_bento.new_record? %>
        <div class="row">
          <div class="col">
            <%= f.text_field :template_name, list: 'bento-template-names' %>
            <datalist id="bento-template-names">
              <% TemplateViewBento.template_names.each do |name| %>
                <option value="<%= name %>"><%= name %></option>
              <% end %>
            </datalist>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= f.select :user_view, options_for_select(UserView.values_for_menus('all'), @template_view_bento.user_view) %>
          </div>
        </div>
      <% end %>
      <div class="row">
        <div class="col">
          <%= f.collection_select(:predefined_bento_id, PredefinedBento.alphabetic, :id, :disambiguated_name, prompt: true) %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= f.number_field :default_order, step: 0.1, help: t('activerecord.help.template_view_bento.default_order') %>
          <%= bs4_switch f, :shown_by_default %>
        </div>
      </div>

    </div>
  </div>

  <%= f.primary 'Submit' %>
<% end %>

app/views/template_view_bentos/_list.html.erb
<div class="row mb-3">
  <div class="col">
    <%== pagy_bootstrap_nav pagy %>
  </div>
  <div class="col">
    <%= displayed_items pagy %>
  </div>
</div>
<div class="row">
  <div class="col">
    <%= render_table template_view_bentos %>
  </div>
</div>
<div class="row">
  <div class="col">
    <%== pagy_bootstrap_nav pagy %>
  </div>
</div>

app/views/template_view_bentos/_sort_and_filter.html.erb
<div class="col">
  <div class="card shadow-sm">
    <div class="card-body">
      <h5 class="card-title">
        <span class="pull-right">
          <%= render_filterrific_spinner %>
        </span>
      </h5>
      <%= form_for_filterrific @filterrific do |f| %>
        <div class="form-row">
          <div class="col form-group">
            <%= f.label :with_template_name, t('app.template_view_bentos.sort_n_filter.options.template_name') %>
            <%= f.select(
                    :with_template_name, @filterrific.select_options[:with_template_name],
                    { include_blank: '- Any -' },
                    class: 'form-control custom-select') %>
          </div>
          <div class="col form-group">
            <%= f.label :with_user_view, t('app.template_view_bentos.sort_n_filter.options.user_view') %>
            <%= f.select(
                  :with_user_view, @filterrific.select_options[:with_user_view],
                  { include_blank: '- Any -' },
                  class: 'form-control custom-select') %>
          </div>
        </div>
        <div class="form-row">
          <div class="col form-group">
            <%= f.label :with_predefined_bento, t('app.template_view_bentos.sort_n_filter.options.predefined_bento') %>
            <%= f.select(
                  :with_predefined_bento, PredefinedBento.menu_values,
                  { include_blank: '- Any -' },
                  class: 'form-control custom-select') %>
          </div>
          <div class="col form-group">
            <%= f.label :with_service_type, t('app.template_view_bentos.sort_n_filter.options.service_type') %>
            <%= f.select(
                  :with_service_type, BentoService.menu_values,
                  { include_blank: '- Any -' },
                  class: 'form-control custom-select') %>
          </div>
        </div>
        <div class="form-row">
          <div class="col form-group">
            <%= f.label :shown_default_state, t('app.template_view_bentos.sort_n_filter.options.shown_by_default') %>
            <%= f.select(
                  :shown_default_state, @filterrific.select_options[:shown_default_state],
                  { include_blank: '- Any -' },
                  class: 'form-control custom-select') %>
          </div>
        </div>

    <% end %>
    </div>
  </div>
</div>

app/views/template_view_bentos/_template_view_bento.html.erb
<tr>
  <th scope="row"><%= template_view_bento.default_order%></th>
  <td><%= link_to template_view_bento.template_name, template_view_bento %></td>
  <td><%= link_to template_view_bento.user_view, template_view_bento %></td>
  <td><%= link_to template_view_bento.predefined_bento.disambiguated_name, template_view_bento.predefined_bento %></td>
  <td><%= template_view_bento.predefined_bento.service_name %></td>
  <td><%= boolean_check_icon template_view_bento.shown_by_default %></td>
  <td><%= action_buttons template_view_bento %></td>
</tr>

app/views/template_view_bentos/_template_view_bentos_table.html.erb
<table class="table">
  <thead>
  <tr>
    <th scope="col"><%= filterrific_sorting_link(
                          @filterrific, :default_order,
                          label: t('activerecord.attributes.template_view_bento.default_order')) %></th>
    <th scope="col"><%= filterrific_sorting_link(
                          @filterrific, :template_name,
                          label: t('activerecord.attributes.template_view_bento.template_name')) %></th>
    <th scope="col"><%= filterrific_sorting_link(
                          @filterrific, :user_view,
                          label: t('activerecord.attributes.template_view_bento.user_view')) %></th>
    <th scope="col"><%= t('activerecord.attributes.template_view_bento.predefined_bento_id') %></th>
    <th scope="col"><%= t('activerecord.attributes.template_view_bento.service_type') %></th>
    <th scope="col"><%= filterrific_sorting_link(
                          @filterrific, :shown_by_default,
                          label: t('activerecord.attributes.template_view_bento.shown_by_default')) %></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <%= render @template_view_bentos %>
  </tbody>
</table>

app/views/template_view_bentos/_template_view_row.html.erb
<td>
  <%= link_to user_view.name, template_view_bentos_path(filterrific: {
    with_template_name: template_name,
    with_user_view: user_view.code}) %>
</td>
<td>
  <div>
    <% visible&.each do |tvb| %>
      <%= link_to tvb.predefined_bento.display_name, template_view_bento_path(tvb), class: 'badge badge-primary' %>
    <% end %>
  </div>
  <div>
    <% hidden&.each do |tvb| %>
      <%= link_to tvb.predefined_bento.display_name, template_view_bento_path(tvb), class: 'badge badge-secondary' %>
  <% end %>
  </div>
</td>

app/views/template_view_bentos/edit.html.erb
<div class="container-fluid edit-template-view-bento-page">
  <div class="row">
    <div class="col">
      <h1><%= "Edit: #{@template_view_bento.title}" %> </h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/template_view_bentos/fork_template_form.erb
<div class="container-fluid fork-bento-template-page">
  <div class="row">
    <div class="col">
      <h1><%= "#{t('app.bento_templates.fork_form_title')}: #{@from_template}" %> </h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <p>
        <%= t('app.bento_templates.fork_message', from_template: @from_template).html_safe %>
      </p>
      <%= bootstrap_form_with scope: 'fork_info', url: fork_bento_template_path, method: 'post' do |f| %>
        <%= f.hidden_field :from, value: @from_template %>
        <%= f.text_field :to, label: "New template name"  %>
        <%= f.select( :institution_ids, @institutions, {label: "Institutions"},
                       class: 'form-control chosen-multiselect', multiple: true)  %>
        <%= f.submit value: 'Fork', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/template_view_bentos/index.html.erb
<div class="container-fluid template-view-bentos-page">
  <div class="row mb-3">
    <div class="col">
      <h1><%= t('app.menu.template_view_bentos') %></h1>
      <%= btn_primary_link t('app.menu.predefined_bentos'), predefined_bentos_path %>
      <%= btn_primary_link t('app.menu.bento_history'), bento_versions_path %>
    </div>
    <div class="col">
      <div class="float-right">
        <%= index_page_buttons @template_view_bentos %>
        <%= show_deleted_bento_btn_link TemplateViewBento if current_user.admin? %>
      </div>
    </div>
  </div>
  <div class="row mb-3">
    <%= render partial: 'sort_and_filter', locals: {
      template_view_bentos: @template_view_bentos, filterrific: @filterrific
    } %>
  </div>
  <div id="template-view-bento-results">
    <%= render partial: 'list', locals: {
      template_view_bentos: @template_view_bentos,
      pagy: @pagy,
      filterrific: @filterrific
    } %>
  </div>
</div>

app/views/template_view_bentos/index.js.erb
<% js = escape_javascript(
  render(partial: 'list', locals: { template_view_bentos: @template_view_bentos, pagy: @pagy })
) %>
$("#template-view-bento-results").html("<%= js %>");

app/views/template_view_bentos/new.html.erb
<div class="container-fluid new-template-view-bento-page">
  <div class="row">
    <div class="col">
      <h1><%= t('app.template_view_bentos.label.new') %> </h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/template_view_bentos/show.html.erb
<div class="container-fluid show-template-view-bento-page">
  <div class="row mb-5">
    <div class="col">
      <h1><%= @template_view_bento.title %></h1>
      <%= btn_primary_link(t('app.defaults.labels.edit'), edit_template_view_bento_path(@template_view_bento)) %>
      <%= link_to(I18n.t('app.defaults.labels.delete'), template_view_bento_path(@template_view_bento),
                  class: 'btn btn-primary ',
                  method: :delete, data: {
          confirm: I18n.t('app.defaults.confirmation.confirm')
        }) %>
    </div>
  </div>
  <ul class="nav nav-tabs mb-2" id="template-view-bento-show-tabs" role="tablist">
    <%= nav_tab_for t('app.template_view_bentos.tabs.general'), true %>
    <%= nav_tab_for t('app.template_view_bentos.tabs.galileo_bentos',
                      count: @template_view_bento.configured_bentos.created_by_state('galileo').size)%>
  </ul>

  <div class="tab-content" id="template-view-bento-show-tab-content">
    <%= nav_tab_pane_for t('app.template_view_bentos.tabs.general'), true do %>
      <%= tab_fields_for @template_view_bento, :general_template_view_bento_fields %>
    <% end %>
    <%= nav_tab_pane_for t('app.template_view_bentos.tabs.galileo_bentos',
                           count: @template_view_bento.configured_bentos.created_by_state('galileo').size) do %>
      <%= render('configured_bentos/tab_configured_bentos_table',
                 configured_bentos: @template_view_bento.configured_bentos.created_by_state('galileo').institution_ordered) %>
    <% end %>
  </div>
</div>

app/views/template_view_bentos/templates.html.erb
<div class="container-fluid template-view-bentos-page">
  <div class="row mb-3">
    <div class="col">
      <h1><%= t('app.menu.template_view_bentos') %></h1>
      <%= btn_primary_link t('app.template_view_bentos.advanced'), template_view_bentos_path %>
      <%= btn_primary_link t('app.menu.predefined_bentos'), predefined_bentos_path %>
      <%= btn_primary_link t('app.menu.bento_history'), bento_versions_path %>
    </div>
    <div class="col">
      <div class="float-right">
        <%= index_page_buttons @template_view_bentos %>
        <%= show_deleted_bento_btn_link TemplateViewBento if current_user.admin? %>
      </div>
    </div>
  </div>
  <div class="mb-3">
    <table class="table">
      <tr>
        <th><%= t('app.bento_templates.columns.name') %></th>
        <th><%= t('app.bento_templates.columns.user_view') %></th>
        <th><%= t('app.bento_templates.columns.bentos') %></th>
        <th><%= t('app.bento_templates.columns.institutions') %></th>
        <th></th>
      </tr>
    <% @templates.each do |template_name, by_view| %>
      <tr>
        <td rowspan="<%= by_view.size %>">
          <%= link_to template_name, template_view_bentos_path(filterrific: {
            with_template_name: template_name,
            with_user_view: ''}) %>
        </td>
        <%= render partial: 'template_view_bentos/template_view_row', locals: {
          template_name: template_name,
          user_view: @user_view_lookup[by_view.keys.first],
          visible: by_view.values.first[true],
          hidden: by_view.values.first[false]
        } %>
        <td rowspan="<%= by_view.size %>">
          <% if @institution_counts[template_name] %>
            <%= link_to @institution_counts[template_name], institutions_path(filterrific: {with_bento_template: template_name}) %>
          <% else %>
            0
          <% end %>
        </td>
        <td rowspan="<%= by_view.size %>">
          <%= link_to 'Fork', fork_bento_template_form_path(template_name), class: 'btn btn-primary' if FeatureFlags.enabled? :flexible_bento_templates %>
        </td>
        <% by_view.keys[1..].each do |k| %>
          </tr><tr>
          <%= render partial: 'template_view_bentos/template_view_row', locals: {
            template_name: template_name,
            user_view: @user_view_lookup[k],
            visible: by_view.dig(k, true),
            hidden: by_view.dig(k, false)
          } %>
        <% end %>
      </tr>
    <% end %>
    </table>
  </div>
</div>