config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # establish distinct root for authenticated users
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated do
    root to: 'redirect#redirect', as: :authenticated_root
  end

  # root for unauthenticated users
  root to: redirect('auth/sign_in')

  # scope devise routes under /auth to avoid conflict with User CRUD
  devise_for :users, path: 'auth', controllers: {
    invitations: 'invitations'
  }
  concern :versionable do
    member do
      get :diff
      get :rollback
    end
  end

  devise_scope :user do
    get 'auth/invitations', to: 'invitations#index'
  end

  namespace :api do
    namespace :v1 do
      constraints(format: :json) do
        get 'ok', to: 'base#ok'
        get 'inst', to: 'auth_support#inst'
      end
    end
  end

  get 'ez_proxy_update', to: 'ez_proxy_update#report'
  get 'ez_proxy_update/:inst_code', to: 'ez_proxy_update#report'

  get 'institutions_for_stats', to: 'institutions_for_stats#report'
  get 'resources_for_stats', to: 'resources_for_stats#report'
  get 'vendors_for_stats', to: 'vendors_for_stats#report'
  get 'vendor_statistics_identifier_for_stats/:resource_code', to: 'vendor_statistics_identifier_for_stats#report', as: 'vendor_statistics_identifier_for_stats'

  resources :institutions, concerns: :versionable do
    resources :resources, controller: 'institution_resources', only: :index, as: 'resources'
    resources :sites, controller: 'institution_sites', except: [:destroy, :new, :create], as: 'sites'
    resources :brandings
    resources :features
    resources :widgets
    resources :bento_configs do
      member do
        get :test_config
        get :eds_content_providers
      end
      collection do
        get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'bento_config'}
      end
    end
    resources :configured_bentos do
      collection do
        post :restore_defaults
        get '/view/(:user_view)', to: 'configured_bentos#reorder', as: 'reorder'
        post '/view/:user_view', to: 'configured_bentos#save_reorder', as: 'save_reorder'
        post '/view/:user_view/restore_defaults', to: 'configured_bentos#restore_defaults_for_view', as: 'restore_defaults_for_view'
        get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'configured_bento'}
      end
    end
    collection do
      get '/deleted', to: 'versions#deleted', defaults: {item_type: 'institution'}
    end
    member do
      get :new_new_password
      get :update_password_asap
      get :notify_current_password
      get :notify_new_password
      get :express_links_report
      get :resources_report
      get :glri_resources_report
      get :institution_serial_count_report
      get :edit_institutional
      patch :update_institutional
    end
  end

  resources :sites

  resources :resources, concerns: :versionable do
    collection do
      get '/deleted', to: 'versions#deleted', defaults: {item_type: 'resource'}
    end
    member do
      get :copy
    end
  end

  resources :contacts, concerns: :versionable do
    collection do
      get '/deleted', to: 'versions#deleted', defaults: {item_type: 'contact'}
      delete :bulk_destroy
      get :bulk_destroy_confirm
    end
    member do
      get :notify_current_password
    end
  end

  resources :users do
    collection do
      get '/deleted', to: 'users#deleted'
    end
    post :undelete, on: :member
  end

  resources :institution_groups do
    resources :features
  end

  resources :users, :vendors, :passwords, :notify_groups, :formats, :subjects, :user_views

  resources :allocations, only: %i[index show edit update]
  resources :versions, only: %i[index show] do
    collection do
      get '/:item_type/deleted', to: 'versions#deleted', as: 'deleted'
    end
    member do
      post :undelete
    end
  end

  resources :reports, only: %i[index] do
    collection do
      get :resources_with_html
      get :resources_url_check
      get :institution_group_ips
      get :institution_resources
      get :institution_glri_resources
      get :institution_express_links
      get :glri_contacts
      get :non_glri_institutions
      get :ez_proxy_update
      get :public_libraries_primary_contacts
      get :vendor_resources
      get :allocations_vendor
      get :allocations_institution
      get :allocations_resource
      get :vendors_for_stats
      get :resources_for_stats
      get :institutions_for_stats
      get :vendor_statistics_identifier_for_stats
      get :glri_allocations
      get :inst_user_emails
      get :all_rows_for
      get :overlapping_ip_addresses
      get :institution_features
      get :institution_group_features
      get :institution_group_contacts
      get :galileo_passwords
      get :resource_keywords
      get :wayfinder_keywords
      get :deleted_contacts
      get :stats_for_snapshots
    end
  end

  resources :tools, only: %i[index] do
    collection do
      get :csv_import, to: 'tools#csv_import_tool'
      put :csv_import, to: 'tools#csv_import'
      get :ip_cache_status, to: 'tools#ip_cache_status_tool'
      put :ip_cache_status, to: 'tools#ip_cache_status'
    end
  end

  get 'bentos', to: 'template_view_bentos#index'
  get 'bento_templates', to: 'template_view_bentos#templates'

  if FeatureFlags.enabled? :flexible_bento_templates
    get 'bento_template/:from/fork', to: 'template_view_bentos#fork_template_form', as: 'fork_bento_template_form'
    post 'bento_template/:from/fork', to: 'template_view_bentos#fork_template', as: 'fork_bento_template'
  end

  resources :template_view_bentos do
    collection do
      get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'template_view_bento'}
    end
  end
  resources :predefined_bentos do
    collection do
      get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'predefined_bento'}
    end
  end
  resources :configured_bentos, only:[:show] do
    collection do
      get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'configured_bento'}
    end
  end

  resources :bento_configs, only:[:show] do
    collection do
      get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'bento_config'}
    end
  end

  resources :bento_versions, only: %i[index show] do
    collection do
      get '/:item_type/deleted', to: 'bento_versions#deleted', as: 'deleted'
    end
    member do
      post :undelete
    end
  end

  resources :banners, concerns: :versionable do
    collection do
      get '/deleted', to: 'versions#deleted', defaults: {item_type: 'banner'}
    end
    member do
      post :undelete
    end
  end

  namespace :stats do
    get '/', to: 'stats#index', as: :index
    delete ':period/delete_all/:table_name', to: 'stats#delete_all', as: :delete_all

    get 'daily/index/:table_name', to: 'daily#index', as: :daily_index
    get 'daily/new_accumulate_range/:table_name', to: 'daily#new_accumulate_range', as: :daily_new_accumulate_range
    post 'daily/accumulate_range/:table_name', to: 'daily#accumulate_range', as: :daily_accumulate_range
    get 'daily/new_delete_range/:table_name', to: 'daily#new_delete_range', as: :daily_new_delete_range
    delete 'daily/delete_range/:table_name', to: 'daily#delete_range', as: :daily_delete_range

    get 'monthly/index/:table_name', to: 'monthly#index', as: :monthly_index
    get 'monthly/new_accumulate/:table_name', to: 'monthly#new_accumulate', as: :monthly_new_accumulate
    post 'monthly/accumulate/:table_name', to: 'monthly#accumulate', as: :monthly_accumulate
    get 'monthly/new_delete_range/:table_name', to: 'monthly#new_delete_range', as: :monthly_new_delete_range
    delete 'monthly/delete_range/:table_name', to: 'monthly#delete_range', as: :monthly_delete_range

    #Problems putting these routes in the raw namespace
    get 'raw/index/:table_name', to: 'raw#index', as: :raw_index
    get 'raw/new_import/:table_name', to: 'raw#new_import', as: :raw_new_import
    post 'raw/import/:table_name', to: 'raw#import', as: :raw_import
    get 'raw/new_delete_range/:table_name', to: 'raw#new_delete_range', as: :raw_new_delete_range
    delete 'raw/delete_range/:table_name', to: 'raw#delete_range', as: :raw_delete_range
  end
end

app/models/institution_group.rb
# frozen_string_literal: true

# represent a grouping of institutions
class InstitutionGroup < ApplicationRecord
  #region includes
  include Featuring
  #endregion

  # region relationships
  has_and_belongs_to_many :legacy_group_institutions, class_name: 'Institution'
  has_many :institutions
  has_many :banners
  # endregion

  # region validations
  validates_presence_of :code
  validates_uniqueness_of :code
  validates_presence_of :inst_type
  validate :allowed_inst_types
  # endregion

  # region scopes
  scope :code_sort, -> { order(code: :asc) }

  scope :with_sites, -> { where(id: InstitutionGroup.joins(:institutions).joins(institutions: :sites).group(:id).select(:id)) }
  # endregion

  # region callbacks
  after_save :reindex_institutions
  # callbacks

  # region class_methods
  # Returns array of valid view types for drop downs in the form
  def self.allowed_inst_types
    [
      %w[Default default],
      ['K-12 School', 'k12'],
      ['Higher Education', 'highered'],
      ['Public Library', 'publiclib']
    ]
  end

  # Returns all allowed inst types as an array
  def self.allowed_inst_type_codes
    InstitutionGroup.allowed_inst_types.map { |t| t[1] }
  end

  def self.options_for_select
    order('LOWER(name)').map { |group| [group.name, group.id] }
  end
  # endregion

  # region public_methods
  # return code if asked for name (useful in polymorphic `Featuring` views)
  def name
    code
  end

  # @return [TrueClass, FalseClass]
  def k12?
    inst_type == 'k12'
  end

  # @return [TrueClass, FalseClass]
  def publiclib?
    inst_type == 'publiclib'
  end

  # Custom verifications
  def allowed_inst_types
    return if InstitutionGroup.allowed_inst_type_codes.include? inst_type

    errors.add(:inst_type, 'not a permitted inst_type')
  end

  def reindex_institutions
    Sunspot.index! institutions if previous_changes['inst_type']
  end

  def code_with_type
    "#{code} (#{inst_type})"
  end

  def display_views?
    ViewService.institution_display_views?(inst_type)
  end
  #endregion
end

app/controllers/institution_groups_controller.rb
# frozen_string_literal: true

# This is the InstitutionGroups controller
class InstitutionGroupsController < ApplicationController
  load_and_authorize_resource

  add_breadcrumb 'Institution Groups', :institution_groups_path

  def index
    @pagy, @institution_groups = pagy(@institution_groups.code_sort)
  end

  def show
    add_breadcrumb @institution_group.code, institution_group_path(@institution_group)
  end

  def new
    @institution_group = InstitutionGroup.new
    add_breadcrumb 'New', new_institution_group_path

  end

  def edit
    add_breadcrumb @institution_group.code, institution_group_path(@institution_group)
    add_breadcrumb 'Edit', edit_institution_group_path(@institution_group)
  end

  def create
    @institution_group = InstitutionGroup.new(institution_group_params)

    if @institution_group.save
      redirect_to @institution_group
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @institution_group.update(institution_group_params)
      redirect_to @institution_group
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @institution_group.destroy
    redirect_to institution_groups_path
  end

  def sidebar_label
    t("app.menu.institution_groups")
  end

  private

  def institution_group_params
    params.require(:institution_group).permit(
      :code, :inst_type,
      institution_ids: []
    )
  end
end

app/helpers/institution_groups_helper.rb
# frozen_string_literal: true

# view-related helper methods for Institution Groups
module InstitutionGroupsHelper
end

app/views/institution_groups/_form.html.erb
<%= bootstrap_form_for @institution_group do |f| %>
  <%= f.alert_message "Errors found that prevented this institution group from being saved:" %>

  <%# General fields %>
  <div class="card mb-3">
    <div class="card-header">General</div>
    <div class="card-body">
      <div class="row">
        <div class="col">
          <%= f.text_field :code %>
        </div>
        <div class="col">
          <%= f.select :inst_type, options_for_select(InstitutionGroup.allowed_inst_types, @institution_group.inst_type)%>
        </div>
      </div>
      <% if @institution_group.new_record? %>
      <div class="row">
        <div class="col">
          <%= f.collection_select :institution_ids, Institution.all, :id, :name_with_code, { include_blank: true }, { class: 'chosen-multiselect', multiple: true } %>
        </div>
      </div>
        <% end %>
    </div>
  </div>

  <%= f.primary %>
<% end %>

app/views/institution_groups/_institution_group.html.erb
<tr>
  <th scope="row"><%= link_to institution_group.code, institution_group %></th>
  <td><%= institution_group.inst_type %></td>
  <th scope="row"><%= institution_group.institutions.count %></th>
  <td><%= action_buttons institution_group %></td>
</tr>

app/views/institution_groups/_institution_groups_table.html.erb
<table class="table">
  <thead>
  <tr>
    <th scope="col"><%= t('activerecord.attributes.institution_group.code') %></th>
    <th scope="col"><%= t('activerecord.attributes.institution_group.inst_type') %></th>
    <th scope="col"><%= t('activerecord.attributes.institution_group.institution_ids') %></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <%= render @institution_groups %>
  </tbody>
</table>

app/views/institution_groups/edit.html.erb
<div class="container-fluid edit-institution-group-page">
  <div class="row">
    <div class="col">
      <h1>Edit <%= @institution_group.code %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/institution_groups/index.html.erb
<div class="container-fluid institution-groups-page">
  <%= render partial: 'shared/index_non_search', locals: {
    results: @institution_groups,
    pagy: @pagy,
    header: 'Institution&nbsp;Groups'.html_safe
  } %>
</div>

app/views/institution_groups/new.html.erb
<div class="container-fluid new-format-page">
  <div class="row">
    <div class="col">
      <h1>New Institution Group</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/institution_groups/show.html.erb
<div class="container-fluid show-institution-group-page">
  <div class="row mb-5">
    <div class="col">
      <h1><%= @institution_group.code %></h1>
      <%= show_page_buttons @institution_group %>
      <%= btn_primary_link 'Features', institution_group_features_path(@institution_group) %>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col">
      <%= render 'shared/attribute',
                 label: t('activerecord.attributes.institution_group.code'),
                 value: @institution_group.code %>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col">
      <%= render 'shared/attribute',
                 label: t('activerecord.attributes.institution_group.inst_type'),
                 value: @institution_group.inst_type %>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col">
      <%= render 'shared/attribute',
                 label: t('activerecord.attributes.institution_group.institutions'),
                 value: linked_item_group(@institution_group.institutions, %i[name]) %>
    </div>
  </div>
</div>