config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # establish distinct root for authenticated users
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated do
    root to: 'redirect#redirect', as: :authenticated_root
  end

  # root for unauthenticated users
  root to: redirect('auth/sign_in')

  # scope devise routes under /auth to avoid conflict with User CRUD
  devise_for :users, path: 'auth', controllers: {
    invitations: 'invitations'
  }
  concern :versionable do
    member do
      get :diff
      get :rollback
    end
  end

  devise_scope :user do
    get 'auth/invitations', to: 'invitations#index'
  end

  namespace :api do
    namespace :v1 do
      constraints(format: :json) do
        get 'ok', to: 'base#ok'
        get 'inst', to: 'auth_support#inst'
      end
    end
  end

  get 'ez_proxy_update', to: 'ez_proxy_update#report'
  get 'ez_proxy_update/:inst_code', to: 'ez_proxy_update#report'

  get 'institutions_for_stats', to: 'institutions_for_stats#report'
  get 'resources_for_stats', to: 'resources_for_stats#report'
  get 'vendors_for_stats', to: 'vendors_for_stats#report'
  get 'vendor_statistics_identifier_for_stats/:resource_code', to: 'vendor_statistics_identifier_for_stats#report', as: 'vendor_statistics_identifier_for_stats'

  resources :institutions, concerns: :versionable do
    resources :resources, controller: 'institution_resources', only: :index, as: 'resources'
    resources :sites, controller: 'institution_sites', except: [:destroy, :new, :create], as: 'sites'
    resources :brandings
    resources :features
    resources :widgets
    resources :bento_configs do
      member do
        get :test_config
        get :eds_content_providers
      end
      collection do
        get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'bento_config'}
      end
    end
    resources :configured_bentos do
      collection do
        post :restore_defaults
        get '/view/(:user_view)', to: 'configured_bentos#reorder', as: 'reorder'
        post '/view/:user_view', to: 'configured_bentos#save_reorder', as: 'save_reorder'
        post '/view/:user_view/restore_defaults', to: 'configured_bentos#restore_defaults_for_view', as: 'restore_defaults_for_view'
        get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'configured_bento'}
      end
    end
    collection do
      get '/deleted', to: 'versions#deleted', defaults: {item_type: 'institution'}
    end
    member do
      get :new_new_password
      get :update_password_asap
      get :notify_current_password
      get :notify_new_password
      get :express_links_report
      get :resources_report
      get :glri_resources_report
      get :institution_serial_count_report
      get :edit_institutional
      patch :update_institutional
    end
  end

  resources :sites

  resources :resources, concerns: :versionable do
    collection do
      get '/deleted', to: 'versions#deleted', defaults: {item_type: 'resource'}
    end
    member do
      get :copy
    end
  end

  resources :contacts, concerns: :versionable do
    collection do
      get '/deleted', to: 'versions#deleted', defaults: {item_type: 'contact'}
      delete :bulk_destroy
      get :bulk_destroy_confirm
    end
    member do
      get :notify_current_password
    end
  end

  resources :users do
    collection do
      get '/deleted', to: 'users#deleted'
    end
    post :undelete, on: :member
  end

  resources :institution_groups do
    resources :features
  end

  resources :users, :vendors, :passwords, :notify_groups, :formats, :subjects, :user_views

  resources :allocations, only: %i[index show edit update]
  resources :versions, only: %i[index show] do
    collection do
      get '/:item_type/deleted', to: 'versions#deleted', as: 'deleted'
    end
    member do
      post :undelete
    end
  end

  resources :reports, only: %i[index] do
    collection do
      get :resources_with_html
      get :resources_url_check
      get :institution_group_ips
      get :institution_resources
      get :institution_glri_resources
      get :institution_express_links
      get :glri_contacts
      get :non_glri_institutions
      get :ez_proxy_update
      get :public_libraries_primary_contacts
      get :vendor_resources
      get :allocations_vendor
      get :allocations_institution
      get :allocations_resource
      get :vendors_for_stats
      get :resources_for_stats
      get :institutions_for_stats
      get :vendor_statistics_identifier_for_stats
      get :glri_allocations
      get :inst_user_emails
      get :all_rows_for
      get :overlapping_ip_addresses
      get :institution_features
      get :institution_group_features
      get :institution_group_contacts
      get :galileo_passwords
      get :resource_keywords
      get :wayfinder_keywords
      get :deleted_contacts
      get :stats_for_snapshots
    end
  end

  resources :tools, only: %i[index] do
    collection do
      get :csv_import, to: 'tools#csv_import_tool'
      put :csv_import, to: 'tools#csv_import'
      get :ip_cache_status, to: 'tools#ip_cache_status_tool'
      put :ip_cache_status, to: 'tools#ip_cache_status'
    end
  end

  get 'bentos', to: 'template_view_bentos#index'
  get 'bento_templates', to: 'template_view_bentos#templates'

  if FeatureFlags.enabled? :flexible_bento_templates
    get 'bento_template/:from/fork', to: 'template_view_bentos#fork_template_form', as: 'fork_bento_template_form'
    post 'bento_template/:from/fork', to: 'template_view_bentos#fork_template', as: 'fork_bento_template'
  end

  resources :template_view_bentos do
    collection do
      get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'template_view_bento'}
    end
  end
  resources :predefined_bentos do
    collection do
      get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'predefined_bento'}
    end
  end
  resources :configured_bentos, only:[:show] do
    collection do
      get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'configured_bento'}
    end
  end

  resources :bento_configs, only:[:show] do
    collection do
      get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'bento_config'}
    end
  end

  resources :bento_versions, only: %i[index show] do
    collection do
      get '/:item_type/deleted', to: 'bento_versions#deleted', as: 'deleted'
    end
    member do
      post :undelete
    end
  end

  resources :banners, concerns: :versionable do
    collection do
      get '/deleted', to: 'versions#deleted', defaults: {item_type: 'banner'}
    end
    member do
      post :undelete
    end
  end

  namespace :stats do
    get '/', to: 'stats#index', as: :index
    delete ':period/delete_all/:table_name', to: 'stats#delete_all', as: :delete_all

    get 'daily/index/:table_name', to: 'daily#index', as: :daily_index
    get 'daily/new_accumulate_range/:table_name', to: 'daily#new_accumulate_range', as: :daily_new_accumulate_range
    post 'daily/accumulate_range/:table_name', to: 'daily#accumulate_range', as: :daily_accumulate_range
    get 'daily/new_delete_range/:table_name', to: 'daily#new_delete_range', as: :daily_new_delete_range
    delete 'daily/delete_range/:table_name', to: 'daily#delete_range', as: :daily_delete_range

    get 'monthly/index/:table_name', to: 'monthly#index', as: :monthly_index
    get 'monthly/new_accumulate/:table_name', to: 'monthly#new_accumulate', as: :monthly_new_accumulate
    post 'monthly/accumulate/:table_name', to: 'monthly#accumulate', as: :monthly_accumulate
    get 'monthly/new_delete_range/:table_name', to: 'monthly#new_delete_range', as: :monthly_new_delete_range
    delete 'monthly/delete_range/:table_name', to: 'monthly#delete_range', as: :monthly_delete_range

    #Problems putting these routes in the raw namespace
    get 'raw/index/:table_name', to: 'raw#index', as: :raw_index
    get 'raw/new_import/:table_name', to: 'raw#new_import', as: :raw_new_import
    post 'raw/import/:table_name', to: 'raw#import', as: :raw_import
    get 'raw/new_delete_range/:table_name', to: 'raw#new_delete_range', as: :raw_new_delete_range
    delete 'raw/delete_range/:table_name', to: 'raw#delete_range', as: :raw_delete_range
  end
end

app/models/user.rb
# frozen_string_literal: true

# GALILEO Admin site user
class User < ApplicationRecord
  # region includes
  include PgSearch::Model
  include InstitutionFilterable
  # endregion

  # region constants
  VALID_ROLES = %w[admin institutional helpdesk].freeze
  VALID_SUBROLES = {
    admin: [],
    institutional: %w[advanced portal],
    helpdesk: []
  }.freeze
  # endregion

  # region relationships
  has_and_belongs_to_many :institutions
  has_many :versions, :class_name => 'Version', :foreign_key => 'whodunnit'
  has_many :contacts, primary_key: 'email', foreign_key: 'email'
  # endregion

  # region  devise
  devise :database_authenticatable, :recoverable, :rememberable, :validatable, :invitable, validate_on_invite: true
  # endregion

  #region callbacks
  before_validation :clean_subroles
  # end_region

  # region validations
  validates_presence_of :role, :first_name, :last_name
  validates_inclusion_of :role, in: VALID_ROLES
  validate :allowed_subroles
  # endregion

  # region pg_search
  pg_search_scope :search_for,
                  against: %i[email role first_name last_name],
                  using: {
                    tsearch: {
                      dictionary: 'english',
                      prefix: true
                    }
                  }
  # endregion

  #region filterrific
  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters:
      %i[sorted_by text_search with_role with_subroles with_institutions]
  )
  # endregion

  # region scopes
  scope :text_search, ->(query) { search_for query }


  scope :active, lambda {
    where('deleted_at IS NULL AND (invitation_sent_at IS NULL OR invitation_accepted_at IS NOT NULL)')
  }

  scope :deleted, lambda {
    where.not(deleted_at: nil)
  }

  scope :pending_invitation_response, lambda {
    where('invitation_sent_at IS NOT NULL AND invitation_accepted_at IS NULL')
  }

  scope :sorted_by, lambda { |sort_option|
    direction = /desc$/.match?(sort_option) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at/ then order "users.created_at #{direction}"
    when /^updated_at/ then order "users.updated_at #{direction}"
    when /^email/ then order "users.email #{direction}"
    when /^role/ then order "users.role #{direction}"
    when /^first_name/ then order "users.first_name #{direction}"
    when /^last_name/ then order "users.last_name #{direction}"

    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  scope :with_role, lambda { |role|
    next unless role

    where(role: role)
  }

  scope :with_subroles, lambda { |*subroles|
    roles = subroles.flatten.reject(&:blank?)
    next if roles.empty?

    where('subroles @> ARRAY[?]::varchar[]', roles)
  }

  many_to_many_institution_scope :with_institutions
  # endregion

  # region public_methods
  def has_role?(role)
    self.role == role
  end
  def has_subrole?(role)
    self.include? role
  end

  def all_roles
    roles = [role]
    roles + subroles
  end


  def admin?
    role == 'admin'
  end

  def non_admin?
    !admin?
  end

  def institutional?
    role == 'institutional'
  end

  def helpdesk?
    role == 'helpdesk'
  end

  def status
    if deleted_at.nil? && (invitation_sent_at.nil? || !invitation_accepted_at.nil?)
      'Active'
    elsif !invitation_sent_at.nil? && invitation_accepted_at.nil?
      'Invited'
    elsif !deleted_at.nil?
      'Deleted'
    else
      'Unknown'
    end
  end

  # instead of deleting, indicate the user requested a delete & timestamp it
  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  # ensure user account is active
  def active_for_authentication?
    super && !deleted_at
  end

  # provide a custom message for a deleted account
  def inactive_message
    !deleted_at ? super : :deleted_account
  end

  def name
    "#{first_name} #{last_name}"
  end

  def name_with_email
    "#{name} (#{email})"
  end

  def clean_subroles
    self.subroles = subroles.uniq.reject(&:blank?)
  end

  def allowed_subroles
    return unless subroles.any?

    bad_subroles = subroles - VALID_SUBROLES[role.to_sym]

    return unless bad_subroles&.any?

    errors.add(:subroles, "invalid subrole for this role: #{bad_subroles.join}")
  end
  # endregion

  # region class_methods
  def self.sort_options
    [
      ['Recently Created', 'created_at_desc'],
      ['Recently Updated', 'updated_at_desc']
    ]
  end

  # Used to populate user emails for filteriffic
  def self.options_for_select
    order('LOWER(email)').map { |e| [e.email, e.id] }
  end
  # endregion
end

app/views/resources/_allocations_table.html.erb
<div class="resources-allocations-table-count mb-2">
  Allocated: <span class="badge badge-primary"><%= resource.allocations.count %></span>
</div>
<table class="table table-striped table-hover">
  <thead class="thead-light">
    <tr>
      <th scope="col"><%= t('app.allocations.columns.allocation') %></th>
      <th scope="col"><%= t('app.defaults.columns.resource_code') %></th>
      <th scope="col"><%= t('app.allocations.columns.institution_name') %></th>
      <th scope="col"><%= t('app.allocations.columns.smart_display') %></th>
      <th scope="col"><%= t('app.allocations.columns.active_resource') %></th>
      <th scope="col"><%= t('app.allocations.columns.has_overrides') %></th>
      <th scope="col"><%= t('app.allocations.columns.subscription_type') %></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% resource.allocations.includes(:institution).each do |allocation| %>
      <tr>
        <th scope="row"><%= show_allocation_cell allocation %></th>
        <td><%= allocation.institution.code %></td>
        <td><%= allocation.institution.name %></td>
        <td><%= boolean_check_icon allocation.smart_display? %></td>
        <td><%= boolean_check_icon allocation.active_resource? %></td>
        <td><%= boolean_check_icon allocation.has_override_urls? %></td>
        <td><%= badge allocation.subscription_type %></td>
        <td><%= edit_allocation_button(allocation) if can? :edit, allocation %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/resources/_form.html.erb
<%= bootstrap_form_for @resource do |f| %>
  <%= f.alert_message "Errors found that prevented this Resource from being saved:" %>
  <%# Basic fields %>
  <div class="card mb-3">
    <div class="card-header">
      Basic Information
    </div>
    <div class="card-body">
      <div class="row mb-2">
        <div class="col">
          <%= f.text_field :name %>
        </div>
      </div>
      <div class="row mb-2">
        <div class="col">
          <%= f.file_field(:logo, accept: 'image/png,image/gif,image/jpeg,image/jpg', help: t('activerecord.help.resource.logo')) %>
          <%= f.check_box :remove_logo if @resource.logo.attached?%>
        </div>
        <div class="col">
          <%= (image_tag(@resource.logo_thumbnail) if @resource.logo.attached? && @resource.logo.variable?) %>
        </div>
      </div>
      <%= f.text_field :short_description %>
      <%= f.text_area :long_description, rows: 5, help:t('activerecord.help.resource.long_description_html') %>
      <%= f.text_field :vendor_name, help: t('activerecord.help.resource.vendor_name')%>
      <% if current_user.institutional? %>
        <%= f.collection_select :institution_id, current_user.institutions.order(:name), :id, :name_with_code, { include_blank: false }, { selected: @resource.institution_id, disabled: !@resource.new_record?, class: 'chosen-select-required' }  %>
      <% end %>
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col">
              <%= bs4_switch f, :display, help: t('activerecord.help.resource.display') %></div>
            <div class="col">
              <%= bs4_switch f, :active, class: 'active_toggle_allocation_warning', help: t('activerecord.help.resource.active') %></div>
            <div class="col">
              <%= bs4_switch f, :bypass_galileo_authentication , help: t('activerecord.help.resource.bypass_galileo_authentication')%></div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%# Admin-only fields %>
  <% if current_user.admin? %>
    <div class="card mb-3">
      <div class="card-header">
        Admin
      </div>
      <div class="card-body">
        <div class="row">
          <% if @resource.new_record? %>
          <div class="col">
            <%= f.text_field :code, help: t('activerecord.help.resource.code')  %>
          </div>
          <% end %>
          <div class="col">
            <%= f.collection_select :vendor_id, Vendor.all, :id, :name_with_code, { include_blank: true }, { class: 'custom-select' } %>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= f.select :resource_category, options_for_select(Resource.allowed_resource_category_types, @resource.resource_category)%>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= bs4_switch f, :include_in_stats %>
          </div>
          <div class="col">
            <%= f.number_field :serial_count, min:0, step:1 %>
          </div>
        </div>
        <%= f.collection_select :parent_id, Resource.all.order(:name).select(:id, :code, :name), :id, :name_with_code, { include_blank: true }, { class: 'chosen-select' } %>
        <% if @resource.new_record? || @resource.glri? %>
          <%= f.collection_select :institution_id, Institution.active.order(:name), :id, :name_with_code, { include_blank: true }, { disabled: !@resource.new_record?, class: 'chosen-select', id: 'glri_institution_select' } %>
        <% end %>
        <% if @resource.new_record? || @resource.central? %>
          <div id="allocation_selects">
          <div class="form-row">
            <div class="col form-group">
              <label for="all_institutions[]">Available Institutions</label>
              <%= select_tag(:all_institutions,
                             options_for_select(@data[:all_institutions]),
                             multiple: true, class: 'form-control', id: 'institutions_select', size: 20) %>
            </div>
            <div class="col-md-1 d-flex align-items-center">
              <div class="btn-toolbar">
                <div class="btn-group-vertical d-flex align-items-center">
                  <button type="button" id="institutions_select_rightSelected" class="btn btn-outline-secondary">
                    <%= fa_icon 'angle-right' %>
                  </button>
                  <button type="button" id="institutions_select_rightAll" class="btn btn-outline-secondary">
                    <%= fa_icon 'angle-double-right' %>
                  </button>
                  <button type="button" id="institutions_select_leftAll" class="btn btn-outline-secondary">
                    <%= fa_icon 'angle-double-left' %>
                  </button>
                  <button type="button" id="institutions_select_leftSelected" class="btn btn-outline-secondary">
                    <%= fa_icon 'angle-left' %>
                  </button>
                </div>
                <div class="btn-group-vertical btn-group-sm d-flex align-items-center mt-2">
                  <button type="button" id="institutions_select_undo" class="btn btn-outline-secondary">
                    <%= fa_icon 'undo' %>
                  </button>
                  <button type="button" id="institutions_select_redo" class="btn btn-outline-secondary">
                    <%= fa_icon 'repeat' %>
                  </button>
                </div>
                <div class="btn-group-vertical btn-group-sm d-flex align-items-center mt-2">
                  <button type="button" id="institutions_select_clear" class="btn btn-outline-secondary">
                    <%= fa_icon 'eraser' %>
                  </button>
                </div>
              </div>
            </div>
            <div class="col">
              <%= f.select :institution_ids, @data[:allocated_institutions], { }, { multiple: true, size: 22, id: 'institutions_select_to' } %>
            </div>
          </div>
          <div class="form-row mb-3">
            <div class="col">
              <div id="selected_count"></div>
            </div>
            <div class="col-md-1"></div>
            <div class="col">
              <div id="allocated_count"></div>
            </div>
          </div>
          <div class="card">
            <div class="card-body">
              <h3>Select Institutions...</h3>
              <div class="form-row">
                <div class="col form-group">
                  <label for="sibling_institutions[]">From Institution Group</label>
                  <%= select_tag(:institution_groups,
                                 options_for_select(@data[:institution_groups]),
                                 class: 'form-control', size: 9) %>
                </div>
                <div class="col form-group">
                  <label for="resource_codes">By Institution Codes</label>
                  <%= text_area_tag :institution_codes, '', class: 'form-control', rows: 6 %>
                </div>
              </div>
              <div class="form-row">
                <div class="col">
                  <button type="button" id="select_from_institution_group" class="btn btn-outline-secondary">
                    Select Above
                  </button>
                </div>
                <div class="col">
                  <button type="button" id="select_from_institution_codes" class="btn btn-outline-secondary">
                    Select Above
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <%# Connection info %>
  <div class="card mb-3">
    <div class="card-header">Connection Information</div>
    <div class="card-body">
      <%= f.text_field :ip_access_url %>
      <%= f.text_field :remote_access_url %>
      <%= f.text_field :open_athens_url %>
      <% if @resource.institution && @resource.institution.open_athens_scope.present? && @resource.institution.open_athens_org_id.present? %>
        <% api_name = if @resource.institution.open_athens_api_name.present?
                  @resource.institution.open_athens_api_name
               else
                  @resource.institution.open_athens_scope
               end %>
        <%= link_to t('app.resources.labels.open_athens_link_generator'),
            "#{t('app.resources.links.open_athens_link_generator')}/#{api_name}/#{@resource.institution.open_athens_org_id}",
            target: "_blank",
            class: 'btn btn-primary btn-sm',
            title: t('app.resources.messages.open_athens_link_generator')
        %>
        <small class="mb-3 form-text text-muted"><%= t('activerecord.help.resource.open_athens_link_generator') %></small>
      <% end %>
      <div class="row mb-3">
        <div class="col">
          <%= bs4_switch f, :open_athens, help: t('activerecord.help.resource.open_athens') %>
        </div>
        <% if current_user.admin? %>
        <div class="col">
          <%= bs4_switch f, :without_open_athens_redirector, help: t('activerecord.help.resource.without_open_athens_redirector') %>
        </div>
        <div class="col">
          <%= bs4_switch f, :oa_proxy, help: t('activerecord.help.resource.oa_proxy') %>
        </div>
        <div class="col">
          <%= bs4_switch f, :proxy_remote, help: t('activerecord.help.resource.proxy_remote') %>
        </div>
        <% end %>
      </div>
      <div class="row">
        <div class="col">
          <%= f.text_field :user_id %></div>
        <div class="col">
          <%= f.text_field :password %></div>
      </div>
      <div class="row">
        <div class="col">
          <%= f.select :credential_display, options_for_select(@data[:credential_display_options], @resource.credential_display) %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= f.text_area :access_note %>
        </div>
      </div>
    </div>
  </div>

  <%# More indexed metadata %>
  <div class="card mb-3">
    <div class="card-header">Searchable Information</div>
    <div class="card-body">
      <div class="row">
        <div class="col">
          <%= f.collection_select :format_ids, Format.all.order(:name), :id, :name, { include_blank: true }, { class: 'chosen-multiselect', multiple: true } %>
        </div>
        <div class="col">
          <%= f.collection_select :subject_ids, Subject.all.order(:name), :id, :name, { include_blank: true }, { class: 'chosen-multiselect', multiple: true } %>
        </div>

        <%# Admin user or K12/Publiclib GLRI %>
        <% if current_user.admin? || (@resource.institution && ViewService.institution_display_views?(@resource.institution.inst_type)) %>
        <div class="col">
          <%= f.collection_select :user_view_ids, UserView.where(full: false).order(:name), :id, :name, { include_blank: true }, { class: 'chosen-multiselect', multiple: true } %>
        </div>
        <% end %>
      </div>
      <%= f.text_area :audience %>
      <%= array_textarea @resource, :keywords, t('activerecord.help.resource.keywords') %>
      <%= f.text_area :language %>
    </div>
  </div>

  <%# Record display info (e.g. not indexed) %>
  <div class="card mb-3">
    <div class="card-header">Display Information</div>
    <div class="card-body">
      <div class="row">
        <div class="col">
          <% if @resource.institution %>
            <%= f.collection_select :branding_id, @resource.institution.brandings, :id, :name, { include_blank: true }, { } %>
          <% elsif current_user.institutional? %>
            <%= f.grouped_collection_select :branding_id, current_user.institutions.with_brandings, :brandings, :name_with_code, :id, :name, { include_blank: true }, { class: 'chosen-select' } %>
          <% else %>
            <%= f.grouped_collection_select :branding_id, Institution.with_brandings, :brandings, :name_with_code, :id, :name, { include_blank: true }, { class: 'chosen-select' } %>
          <% end %>
        </div>
      </div>
      <%= f.text_area :coverage_dates %>
      <%= f.text_area :update_frequency %>
      <%= f.text_field :title_list_url %>
      <%= f.text_field :product_suite %>
    </div>
  </div>

  <%# Notes Section %>
  <div class="card mb-3">
    <div class="card-header">Notes</div>
    <div class="card-body">
      <div class="row">
        <div class="col">
          <%= f.text_area :note, rows: 6 %>
        </div>
        <div class="col">
          <%= f.text_area :special_information, rows: 6 %>
        </div>
      </div>
    </div>
  </div>
  <%= f.primary %>
<% end %>

app/views/resources/_list.html.erb
<div id="resource-results">
  <div class="row mb-3">
    <div class="col">
      <%== pagy_bootstrap_nav pagy %>
    </div>
    <div class="col">
      <% if current_user.admin? %>
      <%= link_to "Download CSV", resources_path(format: :csv, filterrific: hashify_filters(@filterrific)), class: "btn btn-primary float-right ml-2" %>
      <% end %>
      <%= displayed_items pagy %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= render_table resources %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%== pagy_bootstrap_nav pagy %>
    </div>
  </div>
</div>

app/views/resources/_resource.html.erb
<tr class="resource-row">
  <% if FeatureFlags.enabled? :logos_on_index_pages %>
  <th scope="row"><%= link_to(image_tag(resource.logo_thumbnail), resource) if resource.logo_thumbnail %></th>
  <% end %>
  <th scope="row"><%= link_to resource.code, resource %></th>
  <td><%= resource.name %></td>
  <td><%= boolean_check_icon resource.active %></td>
  <td><%= boolean_check_icon resource.display %></td>
  <td><%= boolean_check_icon resource.institution_id %></td>
  <td><%= boolean_check_icon resource.bypass_galileo_authentication %></td>
  <td><%= boolean_check_icon resource.open_athens %></td>
  <td>
    <div class="btn-group btn-group-sm" role="group" aria-label="Resource action buttons">
      <%= link_to(t('app.defaults.labels.edit'), edit_resource_path(resource), class: 'btn btn-outline-primary resource-edit-button') if can?(:update, resource) %>
      <%= link_to(t('app.resources.labels.copy'), copy_resource_path(resource), class: 'btn btn-outline-primary resource-copy-button') if current_user.admin? || (can?(:copy, resource) && resource.active) %>
    </div>
  </td>
</tr>

app/views/resources/copy.html.erb
<div class="container-fluid copy-institution-page">
  <div class="row">
    <div class="col">
      <h1>Copy <%= @resource.name %></h1>
    </div>
  </div>
  <% if current_user.institutional? %>
  <div class="row copy-resource-institutional-messages">
    <div class="col">
      <div class="alert alert-warning" role="alert">
        <%= t('app.resources.messages.copy_warning') %>
      </div>
      <div class="alert alert-info" role="alert">
        <%= t('app.resources.messages.copy_info',
              contact_href: t('app.links.contact')).html_safe %>
      </div>
    </div>
  </div>
  <% end %>
  <div class="row">
    <div class="col">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/resources/index.js.erb
<% js = escape_javascript(
  render(partial: 'list', locals: { resources: @resources, pagy: @pagy })
) %>
$("#resource-results").html("<%= js %>");