config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # establish distinct root for authenticated users
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated do
    root to: 'redirect#redirect', as: :authenticated_root
  end

  # root for unauthenticated users
  root to: redirect('auth/sign_in')

  # scope devise routes under /auth to avoid conflict with User CRUD
  devise_for :users, path: 'auth', controllers: {
    invitations: 'invitations'
  }
  concern :versionable do
    member do
      get :diff
      get :rollback
    end
  end

  devise_scope :user do
    get 'auth/invitations', to: 'invitations#index'
  end

  namespace :api do
    namespace :v1 do
      constraints(format: :json) do
        get 'ok', to: 'base#ok'
        get 'inst', to: 'auth_support#inst'
      end
    end
  end

  get 'ez_proxy_update', to: 'ez_proxy_update#report'
  get 'ez_proxy_update/:inst_code', to: 'ez_proxy_update#report'

  get 'institutions_for_stats', to: 'institutions_for_stats#report'
  get 'resources_for_stats', to: 'resources_for_stats#report'
  get 'vendors_for_stats', to: 'vendors_for_stats#report'
  get 'vendor_statistics_identifier_for_stats/:resource_code', to: 'vendor_statistics_identifier_for_stats#report', as: 'vendor_statistics_identifier_for_stats'

  resources :institutions, concerns: :versionable do
    resources :resources, controller: 'institution_resources', only: :index, as: 'resources'
    resources :sites, controller: 'institution_sites', except: [:destroy, :new, :create], as: 'sites'
    resources :brandings
    resources :features
    resources :widgets
    resources :bento_configs do
      member do
        get :test_config
        get :eds_content_providers
      end
      collection do
        get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'bento_config'}
      end
    end
    resources :configured_bentos do
      collection do
        post :restore_defaults
        get '/view/(:user_view)', to: 'configured_bentos#reorder', as: 'reorder'
        post '/view/:user_view', to: 'configured_bentos#save_reorder', as: 'save_reorder'
        post '/view/:user_view/restore_defaults', to: 'configured_bentos#restore_defaults_for_view', as: 'restore_defaults_for_view'
        get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'configured_bento'}
      end
    end
    collection do
      get '/deleted', to: 'versions#deleted', defaults: {item_type: 'institution'}
    end
    member do
      get :new_new_password
      get :update_password_asap
      get :notify_current_password
      get :notify_new_password
      get :express_links_report
      get :resources_report
      get :glri_resources_report
      get :institution_serial_count_report
      get :edit_institutional
      patch :update_institutional
    end
  end

  resources :sites

  resources :resources, concerns: :versionable do
    collection do
      get '/deleted', to: 'versions#deleted', defaults: {item_type: 'resource'}
    end
    member do
      get :copy
    end
  end

  resources :contacts, concerns: :versionable do
    collection do
      get '/deleted', to: 'versions#deleted', defaults: {item_type: 'contact'}
      delete :bulk_destroy
      get :bulk_destroy_confirm
    end
    member do
      get :notify_current_password
    end
  end

  resources :users do
    collection do
      get '/deleted', to: 'users#deleted'
    end
    post :undelete, on: :member
  end

  resources :institution_groups do
    resources :features
  end

  resources :users, :vendors, :passwords, :notify_groups, :formats, :subjects, :user_views

  resources :allocations, only: %i[index show edit update]
  resources :versions, only: %i[index show] do
    collection do
      get '/:item_type/deleted', to: 'versions#deleted', as: 'deleted'
    end
    member do
      post :undelete
    end
  end

  resources :reports, only: %i[index] do
    collection do
      get :resources_with_html
      get :resources_url_check
      get :institution_group_ips
      get :institution_resources
      get :institution_glri_resources
      get :institution_express_links
      get :glri_contacts
      get :non_glri_institutions
      get :ez_proxy_update
      get :public_libraries_primary_contacts
      get :vendor_resources
      get :allocations_vendor
      get :allocations_institution
      get :allocations_resource
      get :vendors_for_stats
      get :resources_for_stats
      get :institutions_for_stats
      get :vendor_statistics_identifier_for_stats
      get :glri_allocations
      get :inst_user_emails
      get :all_rows_for
      get :overlapping_ip_addresses
      get :institution_features
      get :institution_group_features
      get :institution_group_contacts
      get :galileo_passwords
      get :resource_keywords
      get :wayfinder_keywords
      get :deleted_contacts
      get :stats_for_snapshots
    end
  end

  resources :tools, only: %i[index] do
    collection do
      get :csv_import, to: 'tools#csv_import_tool'
      put :csv_import, to: 'tools#csv_import'
      get :ip_cache_status, to: 'tools#ip_cache_status_tool'
      put :ip_cache_status, to: 'tools#ip_cache_status'
    end
  end

  get 'bentos', to: 'template_view_bentos#index'
  get 'bento_templates', to: 'template_view_bentos#templates'

  if FeatureFlags.enabled? :flexible_bento_templates
    get 'bento_template/:from/fork', to: 'template_view_bentos#fork_template_form', as: 'fork_bento_template_form'
    post 'bento_template/:from/fork', to: 'template_view_bentos#fork_template', as: 'fork_bento_template'
  end

  resources :template_view_bentos do
    collection do
      get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'template_view_bento'}
    end
  end
  resources :predefined_bentos do
    collection do
      get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'predefined_bento'}
    end
  end
  resources :configured_bentos, only:[:show] do
    collection do
      get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'configured_bento'}
    end
  end

  resources :bento_configs, only:[:show] do
    collection do
      get '/deleted', to: 'bento_versions#deleted', defaults: {item_type: 'bento_config'}
    end
  end

  resources :bento_versions, only: %i[index show] do
    collection do
      get '/:item_type/deleted', to: 'bento_versions#deleted', as: 'deleted'
    end
    member do
      post :undelete
    end
  end

  resources :banners, concerns: :versionable do
    collection do
      get '/deleted', to: 'versions#deleted', defaults: {item_type: 'banner'}
    end
    member do
      post :undelete
    end
  end

  namespace :stats do
    get '/', to: 'stats#index', as: :index
    delete ':period/delete_all/:table_name', to: 'stats#delete_all', as: :delete_all

    get 'daily/index/:table_name', to: 'daily#index', as: :daily_index
    get 'daily/new_accumulate_range/:table_name', to: 'daily#new_accumulate_range', as: :daily_new_accumulate_range
    post 'daily/accumulate_range/:table_name', to: 'daily#accumulate_range', as: :daily_accumulate_range
    get 'daily/new_delete_range/:table_name', to: 'daily#new_delete_range', as: :daily_new_delete_range
    delete 'daily/delete_range/:table_name', to: 'daily#delete_range', as: :daily_delete_range

    get 'monthly/index/:table_name', to: 'monthly#index', as: :monthly_index
    get 'monthly/new_accumulate/:table_name', to: 'monthly#new_accumulate', as: :monthly_new_accumulate
    post 'monthly/accumulate/:table_name', to: 'monthly#accumulate', as: :monthly_accumulate
    get 'monthly/new_delete_range/:table_name', to: 'monthly#new_delete_range', as: :monthly_new_delete_range
    delete 'monthly/delete_range/:table_name', to: 'monthly#delete_range', as: :monthly_delete_range

    #Problems putting these routes in the raw namespace
    get 'raw/index/:table_name', to: 'raw#index', as: :raw_index
    get 'raw/new_import/:table_name', to: 'raw#new_import', as: :raw_new_import
    post 'raw/import/:table_name', to: 'raw#import', as: :raw_import
    get 'raw/new_delete_range/:table_name', to: 'raw#new_delete_range', as: :raw_new_delete_range
    delete 'raw/delete_range/:table_name', to: 'raw#delete_range', as: :raw_delete_range
  end
end

app/controllers/institution_sites_controller.rb
# frozen_string_literal: true

# resource related actions for a given institution
class InstitutionSitesController < ApplicationController
  before_action :set_institution
  before_action :set_site, except: [:index, :new]

  add_breadcrumb 'Institutions', :institutions_path

  MULTIVALUED_TEXT_FIELDS = %w[wayfinder_keywords].freeze

  def index
    add_breadcrumb @institution.name, institution_path(@institution)
    add_breadcrumb 'Sites', institution_sites_path(@institution)
    @filterrific = initialize_filterrific(
    @institution.sites,
      params[:filterrific],
      select_options: {
        sorted_by: Site.sort_options,
        for_site_type: Site.allowed_site_types,
        charter_states: Site.charter_states
      }
    )

    @pagy, @sites = pagy(@filterrific.find.accessible_by(current_ability, params[:action].to_sym))
    respond_to do |format|
      format.html
      format.js
      format.csv do
        csv_report, filename = ReportService.sites(@filterrific.find
                                                               .accessible_by(current_ability, params[:action].to_sym))
        send_data csv_report, filename: "#{filename}_#{Time.now.to_s.underscore}.csv"
      end
    end
  end

  def show
    add_breadcrumb @institution.name, institution_path(@institution)
    add_breadcrumb 'Sites', institution_sites_path(@institution)
    add_breadcrumb @site.name, institution_site_path(@institution, @site)

    render 'sites/show'
  end

  def edit
    add_breadcrumb @institution.name, institution_path(@institution)
    add_breadcrumb 'Sites', institution_sites_path(@institution)
    add_breadcrumb @site.name, institution_site_path(@institution, @site)
    add_breadcrumb 'Edit', edit_institution_site_path(@institution, @site)
  end

  def update
    if @site.update(institution_sites_params)
      redirect_to institution_site_path(@institution, @site), notice: 'Site was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def sidebar_label
    t('app.menu.institutions')
  end

  private

  def set_institution
    @institution = Institution.find params[:institution_id]
    authorize! :show, @institution
  end

  def set_site
    @site = Site.find params[:id]
  end

  def institution_sites_params
    prepare_params(
      params.require(:site).permit(:wayfinder_keywords)
    )
  end

  def prepare_params(params)
    params.each do |f, v|
      if v.is_a? Array
        params[f] = v.reject(&:empty?)
        next
      end
      if MULTIVALUED_TEXT_FIELDS.include? f
        params[f] = v.gsub("\r\n", "\n").strip.split("\n")
      end
    end
  end
end

app/views/institution_sites/_form.html.erb
<%= bootstrap_form_for [@institution, @site] do |f| %>
  <%= f.alert_message "Errors found that prevented this site from being saved:" %>

  <%# General fields %>
  <div class="card mb-3">
    <div class="card-header">General</div>
    <div class="card-body">
      <div class="row">
        <div class="col">
          <%= f.text_field :name %>
          <%= f.text_field :code %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= f.select :site_type, options_for_select(Site.allowed_site_types, @site.site_type)%>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= array_textarea @site, :wayfinder_keywords, t('activerecord.help.institution.wayfinder_keywords') %>
        </div>
      </div>
    </div>
  </div>

  <%= f.primary %>
<% end %>

app/views/institution_sites/_list.html.erb
<div id="site-results">
  <div class="row align-items-center mb-3">
    <div class="col">
      <%== pagy_bootstrap_nav pagy %>
    </div>
    <div class="col">
      <%= link_to "Download CSV", institution_sites_path(@institution, format: :csv, filterrific: hashify_filters(@filterrific)), class: "btn btn-primary float-right ml-2" %>
      <%= displayed_items pagy %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= render partial: 'institution_sites/sites_table',  locals: {sites: sites} %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%== pagy_bootstrap_nav pagy %>
    </div>
  </div>
</div>

app/views/institution_sites/_site.html.erb
<tr>
  <th scope="row"><%= link_to site.name, institution_site_path(@institution, site) %></th>
  <td><%= link_to site.code, institution_site_path(@institution, site) %></td>
  <td><%= site.site_type %></td>
  <td><%= boolean_check_icon site.charter %></td>
  <td><%= btn_primary_link(t('app.defaults.labels.edit'), edit_site_path(site)) if current_user.admin? %></td>
  <td><%= btn_primary_link(I18n.t('app.defaults.labels.edit'), edit_institution_site_path(@institution, site)) if current_user.institutional? && can?(:edit_institutional, @institution) %></td>
</tr>

app/views/institution_sites/_sites_table.html.erb
<table class="table">
  <thead>
  <tr>
    <th scope="col"><%= filterrific_sorting_link(
                          @filterrific, :name,
                          label: t('app.defaults.columns.name')) %></th>
    <th scope="col"><%= filterrific_sorting_link(
                          @filterrific, :code,
                          label: t('app.defaults.columns.code')) %></th>
    <th scope="col"><%= filterrific_sorting_link(
                          @filterrific, :site_type,
                          label: t('activerecord.attributes.site.site_type')) %></th>
    <th scope="col"><%= filterrific_sorting_link(
                          @filterrific, :charter,
                          label: t('activerecord.attributes.site.charter')) %></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% sites.each do |site| %>
    <%= render partial: 'institution_sites/site', locals: {site: site} %>
  <% end %>
  </tbody>
</table>

app/views/institution_sites/_sort_and_filter.html.erb
<div class="col">
  <div class="card shadow-sm">
    <div class="card-body">
      <h5 class="card-title">
        <span class="pull-right">
          <%= render_filterrific_spinner %>
        </span>
      </h5>
      <%= form_for_filterrific(@filterrific, html: { id: 'filterrific-no-ajax-auto-submit' } ) do |f| %>
        <div class="form-row">
          <div class="col form-group">
            <label for="filterrific_text_search"><%= t('app.defaults.sort_n_filter.options.search') %></label>
            <%= f.text_field :text_search, class: 'form-control' %>
          </div>
          <div class="col-md-4 form-group">
            <label for="filterrific_sorted_by"><%= t('app.defaults.sort_n_filter.options.sort') %></label>
            <%= f.select(
                  :sorted_by, @filterrific.select_options[:sorted_by], {},
                  class: 'form-control custom-select')
            %>
          </div>
        </div>
        <div class="form-row">
          <div class="col form-group">
            <label for="filterrific_for_types"><%= t('app.sites.sort_n_filter.options.site_type') %></label>
            <%= f.select(
                  :for_site_type, @filterrific.select_options[:for_site_type],
                  { include_blank: '- Any -' },
                  class: 'form-control custom-select') %>
          </div>
          <div class="col form-group">
            <label for="filterrific_charter_state"><%= t('app.sites.sort_n_filter.options.charter') %></label>
            <%= f.select(
                  :charter_state, @filterrific.select_options[:charter_states],
                  { include_blank: '- Any -' },
                  class: 'form-control custom-select') %>
          </div>
        </div>
        <%= f.submit 'Filter', class: 'btn, btn-primary'%>
    <% end %>
    </div>
  </div>
</div>

app/views/institution_sites/edit.html.erb
<div class="container-fluid edit-site-page">
  <div class="row">
    <div class="col">
      <h1>Edit Site: <%= @site.name %> </h1>
      <h2><%= @institution.name %></h2>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= bootstrap_form_with(model: @site, url: institution_site_path(@institution, @site)) do |f| %>
        <%= f.alert_message "Errors found that prevented this site from being saved:" %>

        <%# General fields %>
        <div class="card mb-3">
          <div class="card-header">General</div>
          <div class="card-body">
            <div class="row">
              <div class="col">
                <%= array_textarea @site, :wayfinder_keywords, t('activerecord.help.institution.wayfinder_keywords') %>
              </div>
            </div>
          </div>
        </div>

        <%= f.primary %>
      <% end %>
    </div>
  </div>
</div>

app/views/institution_sites/index.html.erb
<div class="container-fluid sites-page">
  <div class="row">
    <div class="col">
      <h1><%= @institution.name %></h1>
    </div>
    <div class="col">
      <div class="float-right">
        <%= btn_primary_link t('app.sites.label.new_site'), new_site_path(institution_id: @institution) if current_user.admin? %>
      </div>
    </div>
  </div>
  <div class="row mb-3">
    <%= render partial: 'sort_and_filter', locals: {
      sites: @sites,
      filterrific: @filterrific
    } %>
  </div>
  <%= render partial: 'list', locals: {
    sites: @sites,
    pagy: @pagy,
    filterrific: @filterrific
  } %>
</div>

app/views/institution_sites/index.js.erb
<% js = escape_javascript(
  render(partial: 'list', locals: { sites: @sites, pagy: @pagy })
) %>
$("#site-results").html("<%= js %>");